version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: panqueca
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
